const menu = [
  {
    id: 1,
    title: 'Lasanha Bolonhesa',
    category: 'lasanha',
    price: 59.90,
    img: './images/item-1.jpeg',
    desc: `Recheada com carne moida, queijos especiais e nosso molho pomodoro. `,
  },
  {
    id: 2,
    title: 'Lasanha Branca',
    category: 'lasanha',
    price: 55.90,
    img: './images/item-2.jpeg',
    desc: `Creme de espinafre, brócolis e delicioso mix de queijos especiais: grana padano, ricota cremosa e mozzarella.`,
  },
  {
    id: 3,
    title: 'Spaghetti Carbonara',
    category: 'macarrao',
    price: 57.90,
    img: './images/item-3.jpeg',
    desc: `Spaghetti ao molho cremoso de parmesão e pancetta. `,
  },
  {
    id: 4,
    title: 'Pappardelle ao Brasato',
    category: 'macarrao',
    price: 69.90,
    img: './images/item-4.jpeg',
    desc: `Pappardelle envolto em molho alfredo e queijo parmesão, finalizado com brasato assado lentamente e desfiado, decorado com salsinha. `,
  },
  {
    id: 5,
    title: 'Pizza Marguerita',
    category: 'pizza',
    price: 45.90,
    img: './images/item-5.jpeg',
    desc: `Molho pomodoro, mozzarella fresca, fatias de tomate, manjericão e azeite de oliva. `,
  },
  {
    id: 6,
    title: 'Pizza Carbonara',
    category: 'pizza',
    price: 48.90,
    img: './images/item-6.jpeg',
    desc: `Exclusiva combinação de queijos especiais, ovos e pancetta.`,
  },
  {
    id: 7,
    title: 'Bolo de Chocolate',
    category: 'sobremesa',
    price: 34.90,
    img: './images/item-7.jpeg',
    desc: `Bolo de chocolate recheado com creme de chocolate, servido com morango e trufa caseira de chocolate meio amargo.`,
  },
  {
    id: 8,
    title: 'Tiramisú',
    category: 'sobremesa',
    price: 34.90,
    img: './images/item-8.jpeg',
    desc: `Camadas de biscoitos tipo italiano embebidos em café e licor de amaretto, creme de mascarpone com rum e licor de café, cobertos com raspas de chocolate meio amargo. `,
  },
  {
    id: 9,
    title: 'Sucos',
    category: 'bebida',
    price: 13.90,
    img: './images/item-9.jpeg',
    desc: `Laranja e Limão.`,
  },
  {
    id: 10,
    title: 'Refrigerantes',
    category: 'bebida',
    price: 13.90,
    img: './images/item-9.jpeg',
    desc: `Refil.`,
  },
];
export default menu;
